
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@mui/material";
import { theme } from "./theme/theme";
import { Providers } from "./theme/provider";
import StoreProvider from "./store-provider";
import Navbar from "./ui/navbar.tsx/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
         <Providers>
          <StoreProvider>
        <nav>
          <Navbar/>
        </nav>
        
         {children}
        </StoreProvider>
        </Providers>
      </body>
    </html>
  );
}
